require 'simplecov'
SimpleCov.start
require 'minitest/autorun'
require 'minitest/pride'
require './lib/stat_tracker'
require './lib/model/game_team'
require './lib/model/game'
require './lib/model/team'
require './lib/manager/game_teams_manager'
require './lib/manager/manager'
require './lib/manager/teams_manager'
require './lib/manager/games_manager'
# require './lib/module/'
require 'csv'
