require 'simplecov'
SimpleCov.start
require 'csv'
require './lib/game_team'
require './lib/team'
require './lib/game'
require './lib/game_module'
require './lib/team_module'
require './lib/season_module'
require './lib/league_module'
require './lib/stat_tracker'
require 'pry'
