require 'simplecov'
SimpleCov.start
require 'csv'
require_relative 'lib/game_team'
require_relative 'lib/team'
require_relative 'lib/game'
require_relative 'lib/game_module'
require_relative 'lib/team_module'
require_relative 'lib/season_module'
require_relative 'lib/league_module'
require_relative 'lib/stat_tracker'
require 'pry'
