require "simplecov"
SimpleCov.start

require "pry"
require "csv"
require "./lib/stat_tracker"
require "./lib/game"
require "./lib/coach"
require "./lib/game_results"
require "./lib/game_stats"
require "./lib/score"
require "./lib/season"
require "./lib/stats"
require "./lib/team_stats"
require "./lib/team"
