require 'simplecov'
SimpleCov.start
require './lib/stat_tracker'
require './lib/game'
require './lib/game_teams'
require './lib/teams'
require 'pry'
require './lib/game_stats'
require './lib/game_team_stats'
require './lib/team_stats'