require './spec_helper'

RSpec.describe StatTracker do
  describe '#Percentage_home_wins' do
    it 'checks the percentage of home wins' do

      require 'pry'; binding.pry
      expect().to eq()
    end
  end
end


def game_teams_test_data
  [ {:game_id => "2012030221",
    :team_id => "3",
    :HoA => "away",
    :result => "LOSS",
    :settled_in => "OT",
    :head_coach => "John Tortorella",
    :goals => "2",
    :shots => "8",
    :tackles => "44",
    :pim => "8",
    :powerPlayOpportunities => "3",
    :powerPlayGoals => "0",
    :faceOffWinPercentage => "44.8",
    :giveaways =>"17",
    :takeaways => "7"}, 
    {:game_id => "2012030221",
    :team_id => "6",
    :HoA => "home",
    :result => "WIN",
    :settled_in => "OT",
    :head_coach => "Claude Julien",
    :goals => "3",
    :shots => "12",
    :tackles => "51",
    :pim => "6",
    :powerPlayOpportunities => "4",
    :powerPlayGoals => "1",
    :faceOffWinPercentage => "55.2",
    :giveaways =>"4",
    :takeaways => "5"}, 
    {:game_id => "2012030222",
    :team_id => "3",
    :HoA => "away",
    :result => "LOSS",
    :settled_in => "REG",
    :head_coach => "John Tortorella",
    :goals => "2",
    :shots => "9",
    :tackles => "33",
    :pim => "11",
    :powerPlayOpportunities => "5",
    :powerPlayGoals => "0",
    :faceOffWinPercentage => "51.7",
    :giveaways =>"1",
    :takeaways => "4"}, 
    {:game_id => "2012030222",
    :team_id => "6",
    :HoA => "home",
    :result => "WIN",
    :settled_in => "REG",
    :head_coach => "Claude Julien",
    :goals => "3",
    :shots => "8",
    :tackles => "36",
    :pim => "19",
    :powerPlayOpportunities => "1",
    :powerPlayGoals => "0",
    :faceOffWinPercentage => "48.3",
    :giveaways =>"16",
    :takeaways => "6"}, 
    {:game_id => "2012030223",
    :team_id => "6",
    :HoA => "away",
    :result => "WIN",
    :settled_in => "REG",
    :head_coach => "Claude Julien",
    :goals => "2",
    :shots => "8",
    :tackles => "28",
    :pim => "6",
    :powerPlayOpportunities => "0",
    :powerPlayGoals => "0",
    :faceOffWinPercentage => "61.8",
    :giveaways =>"10",
    :takeaways => "7"}, 
    {:game_id => "2012030223",
    :team_id => "3",
    :HoA => "home",
    :result => "LOSS",
    :settled_in => "REG",
    :head_coach => "John Tororella",
    :goals => "1",
    :shots => "6",
    :tackles => "37",
    :pim => "2",
    :powerPlayOpportunities => "2",
    :powerPlayGoals => "0",
    :faceOffWinPercentage => "38.2",
    :giveaways =>"7",
    :takeaways => "9"} ]
  end